### ISSUE TITLE
Python Wrapper or REST interface?

### ISSUE THREAD

**Issue by vineetvermait** [dair-iitd/OpenIE-standalone#10]
Hi 

Is there a plan to provide REST API or any python wrapper for this library...

REST API could provide a lot of ease to use in other application languages other than Scala

**Comment by swarnaHub** [comment]
Currently no. However, creating a python wrapper over the openie jar should be easy. I know people who are already doing it. Check out the repository - https://github.com/Srivatsava/manualExtraction.

**Comment by nooralahzadeh** [comment]
Any plan to make a server like CoreNLP server?

**Comment by vaibhavad** [comment]
Hi, the link given above seems broken. Can you give some more details on how to run OpenIE as a server or API?

**Comment by dongyt2004** [comment]
Hi, the link "https://github.com/Srivatsava/manualExtraction" seems broken. Can you give some more details on how to run OpenIE as a server or API?

**Comment by vaibhavad** [comment]
We have added the functionality to run OpenIE as a server to be accessed via REST interface - https://github.com/dair-iitd/OpenIE-standalone#running-as-http-server

We have also developed a Python wrapper around OpenIE server - https://github.com/vaibhavad/python-wrapper-OpenIE5
