### ISSUE TITLE
OpenIE 5.0 doesn't work as expected - examples give different, inadequate result

### ISSUE THREAD

**Issue by azelk** [dair-iitd/OpenIE-standalone#11]
I've installed OpenIE 5.0 standalone but it doesn't give adequate results:

```
>java -Xmx4g -XX:+UseConcMarkSweepGC -jar openie-assembly-5.0-SNAPSHOT.jar
* * * * * * * * * * * * *
* OpenIE 5.0 is ready *
* * * * * * * * * * * * *
Jack and Jill visited India, Japan and South Korea
0,94 (Jack and Jill; visited; India, Japan and South Korea)

```
Instead of 6 triples as promised on the front page, it gives just one.
I also tried my own example:
```
Minovic managed and owned the firm SKVM-30000
0,92 (Minovic; owned; the firm SKVM-30000)
0,77 (Minovic; managed; )
```
Which doesn't look adequate either

**Comment by swarnaHub** [comment]
Which version of Open IE are you using? Open IE 5.0 requires 10GB of memory to run as opposed to 4GB which you have specified. I think you are still using the previous version.

**Comment by azelk** [comment]
I've thought that too, but the program itself writes that she is OpenIE 5.0 and I've downloaded it there https://codeload.github.com/dair-iitd/OpenIE-standalone/tar.gz/v5.0
Perhaps it is an old version, labeled as 5.0. I'll try master and check if it helps

**Comment by vineetvermait** [comment]
Any Update on the issue..?/

I am facing the same type of issue...

> Jack and Jill visited India, Japan and South Korea.

Output:

> Jack visited India
> Jack visited Jill

Working on 8GB memory though

**Comment by swarnaHub** [comment]
You are probably using the previous version of Open IE. Clone the latest code from the repository. And you'd need a 16GB machine to run it.
