### ISSUE TITLE
Facing errors in running the project in ubuntu through command prompt

### ISSUE THREAD

**Issue by Renuk9390** [dair-iitd/OpenIE-standalone#15]
I have followed the steps given on github for running the project.

I am using Ubuntu, kept all the necessary jars as mentioned on github also the language model.
I have installed sbt,try to run with the command mentioned on github(

sbt 'run-main edu.knowitall.openie.OpenIECli'

)

I am attaching the error i got and also the project directory in my computer.
can i get any suggestions please ?

[info] Running edu.knowitall.openie.OpenIECli 
[info] Loading feature templates.
[info] Loading models.
[info] Loading lexica.
[info] Loading configuration.
[info] Loading feature templates.
[info] Loading models.
[info] Loading feature templates.
[info] Loading models.
[info] Loading lexica.
[info] Loading feature templates.
[info] Loading models.
[info] Loading feature templates.
[info] Loading models.
[info] Loading lexica.
[error] SLF4J: Class path contains multiple SLF4J bindings.
[error] SLF4J: Found binding in [jar:file:/home/renu/OpenIE-standalone/lib/BONIE.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/home/renu/OpenIE-standalone/lib/ListExtractor.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: Found binding in [jar:file:/home/renu/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[error] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[error] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] Loading feature templates.
[info] Loading models.
[info] Loading lexica.
[info] Initializing Language Model
[info] #
[error] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000000060ad38000, 1302343680, 0) failed; error='Cannot allocate memory' (errno=12)
[info] # There is insufficient memory for the Java Runtime Environment to continue.
[info] # Native memory allocation (mmap) failed to map 1302343680 bytes for committing reserved memory.
[info] # An error report file with more information is saved as:
[info] # /home/renu/OpenIE-standalone/hs_err_pid6259.log
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code returned from runner: 1
[error] Total time: 3648 s, completed May 7, 2018 11:10:30 PM

many thanks,
Renuka

**Comment by swarnaHub** [comment]
Closing the issue as it is resolved..
