### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by eyobn** [dair-iitd/OpenIE-standalone#17]
I was trying to run the OpenIE5.0 following the instruction in the build section. I have followed every steps but finally the project failed to compile properly. I was able to run OpenIE 4.2 but i failed to succeed with this one. The errors persist in all the running alternatives:-
1. sbt compile
2. sbt 'run-main edu.knowitall.openie.OpenIECli'
3. sbt clean compile assembly
4. sbt -J-Xmx10000M clean compile assembly
It keeps generating 9 errors 
- not found: value MayIHelpYou
- not found: type OnreExtraction
- not found: value ListExtractorMainHelpers
- not found: value ListExtractorLanguageModelBasedExtractor
Please if anyone has resolved these issues i need your help. i have attached the screen shot of the errors here.
![error](https://user-images.githubusercontent.com/23556302/40295170-fa0878f6-5d0a-11e8-9631-87a9d837a6a2.png)

**Comment by swarnaHub** [comment]
Here is the standalone jar for Open IE 5.0 - https://drive.google.com/file/d/0B9L6Jr6rcJcKZG1idDB6eGp4cTg/view

Download this and see if it works. You would still need the Language Model file and Wordnet.

**Comment by eyobn** [comment]
@swarnaHub Thank you. It helped. I am running it on 8GB and i think it is below the requirement. Is there any way it could run faster, i can not upgrade the memory in the mean time. it is running in command line environment but very slow.

**Comment by swarnaHub** [comment]
I can't really help you with that because the Language Model itself takes 10 GB of RAM to run. If you wish to run it on an 8 GB machine, use Open IE 4.2.

**Comment by eyobn** [comment]
so what am i getting is not OpenIE 5.0 or what? look below
eyob@eyob-OptiPlex-7050:~/OpenIE-standalone$ java -Xmx10g -XX:+UseConcMarkSweepGC -jar openie-assembly.jar
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   25017
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

Loading feature templates.
Loading models.
Loading lexica.
Loading configuration.
Loading feature templates.
Loading models.
Loading feature templates.
Loading models.
Loading lexica.
Loading feature templates.
Loading models.
Loading feature templates.
Loading models.
Loading lexica.
Loading feature templates.
Loading models.
Loading lexica.
Initializing Language Model
* * * * * * * * * * * * *
* OpenIE 5.0 is ready *
* * * * * * * * * * * * *
Jack and Jill visited India, Japan and South Korea.
Jack and Jill visited India, Japan and South Korea.
0.88 (Jill; visited; South Korea)
0.88 (Jill; visited; Japan)
0.88 (Jill; visited; India)
0.88 (Jack; visited; South Korea)
0.88 (Jack; visited; Japan)
0.88 (Jack; visited; India)

**Comment by swarnaHub** [comment]
Yes, what you are seeing is indeed Open IE 5. I was suggesting that if you wish to get faster extractions on an 8 GB machine, use Open IE 4.2. There's no way I can reduce the memory requirements of Open IE 5.

**Comment by eyobn** [comment]
I understand now the 10GB is for faster extraction and it is not the minimum requirement. Thank you so much for the help.

**Comment by swarnaHub** [comment]
Closing the issue as it has been resolved.

**Comment by eyobn** [comment]
satisfied. just do it!
