### ISSUE TITLE
Issue in running with sbt

### ISSUE THREAD

**Issue by ghost** [dair-iitd/OpenIE-standalone#24]
I am trying to run with sbt when I encounter the following error:

object iitd is not a member of package edu

**Comment by swarnaHub** [comment]
I don't think you have downloaded the pre-compiled jars or if you have, they are not in the right folders. Please read the build section of the ReadMe carefully.

**Comment by ghost** [comment]
I had to put the jar files in the correct folders. Thank you!

**Comment by Fortune-Don** [comment]
Could you tell me which one is the correct folders for the pre-compiled jars?
