### ISSUE TITLE
The phrase "be leveraged" seems to stop OpenIE working

### ISSUE THREAD

**Issue by nlothian** [dair-iitd/OpenIE-standalone#3]
If I attempt to run OpenIE (in interactive command line mode) on the sentence: 
> It can be leveraged. 

I obtain no response until I enter another sentence. I've managed to isolate this behavior somewhat.

Things that work:

```
I z not leveraged.
0.27813615858960106		SimpleArgument(I,List({0}))	Relation(z not,List([2, 7)))	SimpleArgument(leveraged,List([8, 17)))	I z not leveraged.
I z xx leveraged.
0.27813615858960106		SimpleArgument(I,List({0}))	Relation(z,List({2}))	SimpleArgument(xx leveraged,List([4, 16)))	I z xx leveraged.
I z ba leveraged.
0.27813615858960106		SimpleArgument(I,List({0}))	Relation(z,List({2}))	SimpleArgument(ba,List([4, 6)))	I z ba leveraged.
I can be lever.
0.45170382506656653		SimpleArgument(I,List({0}))	Relation(can be,List([2, 8)))	SimpleArgument(lever,List([9, 14)))	I can be lever.
I can be leverageized.
0.1948871917044894		SimpleArgument(I,List({0}))	Relation(can be leverageized,List([2, 21)))		I can be leverageized.
It can be leverage for good.
0.45170382506656653		SimpleArgument(It,List([0, 2)))	Relation(can be,List([3, 9)))	SimpleArgument(leverage for good,List([10, 27)))	It can be leverage for good.
```

However, the following do not work:

```
I can be leveraged.
It can be leveraged.
I x be leveraged.
It can be leveraged for good.
```

Note that "be lever" and "be leverageized" work fine, and it seems to only be the specific combination of "be leveraged" which stops it working.

Here's a screenshot of what I'm seeing. I'm using the phrase "I cat." to get OpenIE to work again.

![image](https://user-images.githubusercontent.com/117304/32206537-9cf9a838-be45-11e7-8b1a-6fc94b443b44.png)

This seems a little unusual. Why is it happening?

**Comment by swarnaHub** [comment]
This is a little strange given that changing the word 'leveraged' to 'leverage' works. I also checked Open IE 4(the previous version) and saw that the issue persists there too.

I will debug it once I get some bandwidth. It'd be great if you can figure out a workaround in the meantime(may be by changing the word).

**Comment by nlothian** [comment]
Thanks for checking this, I thought I was going insane. I'll try to debug further, but a superficial look doesn't find anything obvious.
