### ISSUE TITLE
Location of openie-assembly jar

### ISSUE THREAD

**Issue by rajiv256** [dair-iitd/OpenIE-standalone#30]
In the documentation README, the location and the name of openie-assembly jar wasn't properly specified. 

`java -Xmx10g -XX:+UseConcMarkSweepGC -jar openie-assembly.jar` was the command given. 

But I found the jar here: `OpenIE-standalone/target/scala-2.10/openie-assembly-5.0-SNAPSHOT.jar`. Not sure if this was overlooked.

**Comment by swarnaHub** [comment]
Yes, that's the path! Will update the README.
