### ISSUE TITLE
How to run with sbt and run from a stand-alone jar properly?

### ISSUE THREAD

**Issue by Fortune-Don** [dair-iitd/OpenIE-standalone#32]
I have done compiling properly. But I still have some wrong with the process of running.

When I run with sbt, the error is as follows：
[warn] No sbt.version set in project/build.properties, base directory: /home/tfc/OpenIE-standalone-master/sbt/bin
[info] Set current project to bin (in build file:/home/tfc/OpenIE-standalone-master/sbt/bin/)
[info] Running edu.knowitall.openie.OpenIECli 
[error] (run-main-0) java.lang.ClassNotFoundException: edu.knowitall.openie.OpenIECli
[error] java.lang.ClassNotFoundException: edu.knowitall.openie.OpenIECli
[error] 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 8 s, completed Jul 12, 2019 10:34:28 AM

When I run  from a stand-alone jar, the error is as follows:
[warn] No sbt.version set in project/build.properties, base directory: /home/tfc/OpenIE-standalone-master/sbt/bin
[info] Set current project to bin (in build file:/home/tfc/OpenIE-standalone-master/sbt/bin/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 1 s, completed Jul 12, 2019 10:35:50 AM
[info] Updating ...
[info] Done updating.
[success] Total time: 3 s, completed Jul 12, 2019 10:35:54 AM
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':'
[error] Not a valid key: assembly
[error] assembly
[error]         ^

Could you tell me how to fix this issue?

**Comment by vaibhavad** [comment]
Please confirm that OpenIE-standalone-master/project/build.properties file is present. Also verfiy that sbt version is specified in this file. If not, please update the file from https://github.com/dair-iitd/OpenIE-standalone/blob/master/project/build.properties
