### ISSUE TITLE
Errors while executing compile.sh

### ISSUE THREAD

**Issue by feryah** [dair-iitd/OpenIE-standalone#35]
Hello,

Despite the following of instructions, I still get these errors. Any help please?

[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIE.scala:25:12: object iitd is not a member of package edu
[error] import edu.iitd.cse.open_nre.onre.helper.MayIHelpYou
[error]            ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIE.scala:26:12: object iitd is not a member of package edu
[error] import edu.iitd.cse.open_nre.onre.domain.OnreExtraction
[error]            ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIE.scala:27:12: object iitd is not a member of package edu
[error] import edu.iitd.cse.openieListExtractor.helper.ListExtractorMainHelpers
[error]            ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIE.scala:121:27: not found: type OnreExtraction
[error]     def convertOnre(inst: OnreExtraction): Instance = {
[error]                           ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIE.scala:122:24: not found: type OnreExtraction
[error]       def arg2s (inst: OnreExtraction) = {
[error]                        ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIE.scala:153:24: not found: value ListExtractorMainHelpers
[error]     var newSentences = ListExtractorMainHelpers.helperMainSentences(parser, parsed).asScala
[error]                        ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIE.scala:177:23: not found: value MayIHelpYou
[error]       val onreExtrs = MayIHelpYou.runMe(parsed).asScala.keys;
[error]                       ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIECli.scala:22:12: object iitd is not a member of package edu
[error] import edu.iitd.cse.openieListExtractor.extractors.ListExtractorLanguageModelBasedExtractor
[error]            ^
[error] /home/tim/.local/share/Trash/files/OpenIE-standalone-master/src/main/scala/edu/knowitall/openie/OpenIECli.scala:197:5: not found: value ListExtractorLanguageModelBasedExtractor
[error]     ListExtractorLanguageModelBasedExtractor.languageModel = ListExtractorLanguageModelBasedExtractor.getLanguageModel()
[error]     ^
[error] 9 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 95 s, completed 31 oct. 2019 19:40:52

**Comment by feryah** [comment]
Problem solved.

**Comment by TickTack-z** [comment]
Hi. I faced similar problem, how do you solved this?

**Comment by mingdachen** [comment]
@feryah Hi, I am also having this issue. How did you solve this?
