### ISSUE TITLE
Can't get it running on the HTTP server

### ISSUE THREAD

**Issue by ahaque2** [dair-iitd/OpenIE-standalone#39]
Executing 'java -jar openie-assembly.jar --httpPort 8000', gives following error.

Error: Unknown argument '--httpPort'
Error: argument input-file failed when given '8000'. requirement failed: input file does not exist: 8000

Am I missing out something? Any help is greatly appreciated.

**Comment by vaibhavad** [comment]
Hi, please check if you have the latest changes. In particular check if RootHandler.scala file is present in OpenIE-standalone/src/main/scala/edu/knowitall/openie directory. If not please update your project with the latest changes on Github

**Comment by ahaque2** [comment]
Thanks for your quick response.

I checked and all required files are present under OpenIE-standalone/src/main/scala/edu/knowitall/openie directory

Though I think its better to point out the first point of error that I get during installation.

On running compile.sh under roor directory, the sbt build is failing for 'srlie' with following missing dependencies:

  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-pgp;0.8.1: not found
[warn]  :: com.eed3si9n#sbt-assembly;0.9.2: not found
[warn]  :: com.github.gseitz#sbt-release;0.8: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]

sbt build also fails for the root project with the following missing dependencies:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: edu.washington.cs.knowitall.srlie#srlie_2.10;1.0.4-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

Each of these unresolved dependencies are mentioned in plugins.sbt files and for some reason isnt getting added I guess. 
Can you please suggest some workaround or how to fix this?

Also, do we need to build the whole project or can we directly use the 'openie-assembly.jar'. I ask this as I plan to use the python wrapper library of this project. Can you specify what steps can I ignore in that case?

**Comment by vaibhavad** [comment]
Looks like this is an issue with resolving sbt plugins. I could not replicate it on my machine. An alternative is to manually load sbt plugins as suggested here -https://github.com/sbt/sbt-assembly/issues/245

However this will be long and tedious process. You can directly use the openie-assembly.jar from here - https://drive.google.com/file/d/19z8LO-CYOfJfV5agm82PZ2JNWNUPIB6D/view?usp=sharing . It includes the latest changes of running OpenIE as a server. We still have to test it across different OS versions though.

Do let me know if you are successfully run the pre-compiled jar.

Thanks

**Comment by ahaque2** [comment]
Thanks for sharing the latest jar file. With the new jar file, I was able to start the server and use the python wrapper successfully on my 'Ubuntu 16.04.6 LTS'.

Greatly appreciate your help. Keep up the good work.
