### ISSUE TITLE
error from import edu.iitd

### ISSUE THREAD

**Issue by krullgit** [dair-iitd/OpenIE-standalone#4]
Hello,
I'm trying to execute the project but run into following error:
[error] import edu.iitd.cse.open_nre.onre.helper.MayIHelpYou
[error.txt](https://github.com/dair-iitd/OpenIE-standalone/files/1441118/error.txt)
Thanks for your help in advance,
Matthes

**Comment by swarnaHub** [comment]
You are not downloading the BONIE jar mentioned in the build section. Read the build section carefully.

**Comment by krullgit** [comment]
Thanks for your help. Loading will take a while.
I have another question, but don't know if this is the right place for it.
I want to migrate an openIE system to the german language. Do you have any idea if this would be possible in a reasonable amount of time (regarding the openIE 5)?
I'm asking for my bachelor thesis. 
Best regards,
Matthes

**Comment by swarnaHub** [comment]
Open IE works on sentence patterns. So for a different language like German, the patterns will be different. However, the same ideas of pattern learning can still work. Please look at the relevant research papers to have a better idea of how Open IE works. You can also check out relevant literature of Open IE in German and see if anything concrete exists.
Closing the issue as the main query has been resolved.
