### ISSUE TITLE
Phrase causes fatal OpenIE fatal error

### ISSUE THREAD

**Issue by soldni** [dair-iitd/OpenIE-standalone#5]
Hi,

During normal usage of OpenIE, I've found out that the following sentence causes a crash:

```
An evaluation of our system against the annotated data shows that, it successfully classifies 73.2% in a German corpus of 2.284 SRHs as either coherent or incoherent (given a baseline of 54.55%).
```
In particular, the following error is raised (the full stacktrace is [available here](https://github.com/dair-iitd/OpenIE-standalone/files/1549059/stacktrace.log)):

```
Exception in thread "main" java.util.regex.PatternSyntaxException: Unclosed group near index 109
(?i).*\bas either coherent or incoherent ( given a baseline of 54.55 % ; in a German corpus of 2.284 SRHs\b.*
```

Curiously, removing the final "s" in SHR seems to fix the issue. Any idea of what might be going on?

**Comment by swarnaHub** [comment]
A regex matching code is causing the exception. I'll try to fix it soon. I am guessing removing the 's' should work for you now. You can additionally pass the "--ignore-errors" flag to continue running your code even if an exception is encountered.

**Comment by bhadramani** [comment]
It is recommended to use --ignore-errors. I believe it writes these to a file, if you can post that file, it 'll be a great help to current researchers.
