### ISSUE TITLE
Why OpenIE 5.0 is much much slower than Reverb?

### ISSUE THREAD

**Issue by wolfshow** [dair-iitd/OpenIE-standalone#7]
I think Reverb is super fast. Why is this version so slow?

**Comment by swarnaHub** [comment]
Reverb used hand crafted features. Between Reverb and Open IE 5.0 a lot of changes have gone in. The history of Open IE has been summarized in the following paper - http://www.cse.iitd.ac.in/~mausam/papers/ijcai16a.pdf
