### ISSUE TITLE
Assembling jar doesn't work

### ISSUE THREAD

**Issue by nitishgupta** [dair-iitd/OpenIE-standalone#8]
UPDATE: I did this on a different machine with the same sbt, scala and java versions and it worked. Any ideas, why?
-------
I tried using  ```sbt -J-Xmx10000M clean compile assembly```  to generate a stand-alone jar but the command halts after 
```All tests passed```
I tried running the command with a lot more RAM as well. Any idea?

P.S. ```sbt compile``` works fine. The command line interface also starts.

**Comment by swarnaHub** [comment]
Are you on windows? If yes, switch to Ubuntu/OS X. Open IE traditionally has some problems with windows.

**Comment by nitishgupta** [comment]
I'm not using Windows. It didn't work on Ubuntu for me, but worked on OS X.

**Comment by swarnaHub** [comment]
Great! Closing the issue.

**Comment by samira-ghodratnama** [comment]
There is no way that it works on windows?
