### ISSUE TITLE
Issue with few below sentences

### ISSUE THREAD

**Issue by skprasadu** [dair-iitd/OpenIE-standalone#9]
First off, I want to acknowledge that this is a awesome tool. I love it. I was able to integrate this with my Java pipeline and it works like a charm.

Some of our sentences are not getting extracted, we think it is a proper sentence, but it is not getting extracted. Can you tell us the reason?

APPLICANT MUST INFORM CONSIGNEE OF ALL LICENSE CONDITIONS

ENSURE THAT EMPLOYEES DO NOT RECEIVE CONTROLLED TECHNOLOGY UNTIL AUTHORIZED BY  AUTHORITY

Everything else worked like a charm. See if you can help us.

**Comment by swarnaHub** [comment]
Open IE essentially works on dependency patterns. It might be that these sentences aren't matching any of the patterns. Could you try changing the sentences to lower case and see it that gives you extractions.

**Comment by skprasadu** [comment]
Thanks Swarna, that helped.

I have one more question, is there a way to train this?

**Comment by swarnaHub** [comment]
No.. The biggest strength of Open IE is that it is domain-independent. So it doesn't require explicit training on any dataset. Check out the history of Open IE at http://www.cse.iitd.ac.in/~mausam/papers/ijcai16a.pdf to understand better.
